// Compact starter list: well-known third-party ad, tracking and fingerprinting
// hosts, plus a few conservative path rules and hiding selectors. It is meant to
// be small enough to ship in the service worker. Load EasyList for full coverage.
export const DEFAULT_LIST = `
! --- ad networks / exchanges ---
||doubleclick.net^$third-party
||googlesyndication.com^
||googleadservices.com^
||adservice.google.com^
||pagead2.googlesyndication.com^
||2mdn.net^
||adnxs.com^
||adsrvr.org^
||advertising.com^
||adform.net^
||amazon-adsystem.com^
||criteo.com^
||criteo.net^
||casalemedia.com^
||contextweb.com^
||openx.net^
||pubmatic.com^
||rubiconproject.com^
||smartadserver.com^
||bidswitch.net^
||sharethrough.com^
||3lift.com^
||yieldmo.com^
||teads.tv^
||media.net^$third-party
||adsafeprotected.com^
||moatads.com^
||serving-sys.com^
||zedo.com^
||taboola.com^$third-party
||outbrain.com^$third-party
||revcontent.com^
||mgid.com^
||adroll.com^
||bounceexchange.com^
||popads.net^
||popcash.net^
||propellerads.com^
||exoclick.com^
||juicyads.com^
||trafficjunky.net^
||trafficfactory.biz^
||adcash.com^
||ad-maven.com^
||clickadu.com^
||hilltopads.net^
||adskeeper.com^
||yandexadexchange.net^
||an.yandex.ru^
||mc.yandex.ru^$third-party
||adtechus.com^
||lijit.com^
||indexww.com^
||spotxchange.com^
||springserve.com^
||tremorhub.com^
||undertone.com^
||adition.com^
||inmobi.com^
||applovin.com^$third-party
||unityads.unity3d.com^
||ads.twitter.com^
||ads.linkedin.com^
||ads.pinterest.com^
||ads.yahoo.com^
||analytics.yahoo.com^
||advertising.amazon.com^
! --- analytics / tracking ---
||google-analytics.com^
||googletagmanager.com^$third-party,script
||googletagservices.com^
||stats.g.doubleclick.net^
||scorecardresearch.com^
||quantserve.com^
||quantcount.com^
||chartbeat.com^
||chartbeat.net^
||parsely.com^$third-party
||hotjar.com^$third-party
||fullstory.com^$third-party
||mouseflow.com^
||crazyegg.com^
||luckyorange.com^
||inspectlet.com^
||mixpanel.com^$third-party
||segment.io^
||amplitude.com^$third-party
||heapanalytics.com^
||krxd.net^
||bluekai.com^
||demdex.net^
||omtrdc.net^
||everesttech.net^
||2o7.net^
||agkn.com^
||rlcdn.com^
||tapad.com^
||liadm.com^
||pippio.com^
||addthis.com^$third-party
||sharethis.com^$third-party
||disqusads.com^
||facebook.com/tr^
||facebook.com/tr/
||connect.facebook.net/*/fbevents.js
||analytics.tiktok.com^
||snap.licdn.com^
||px.ads.linkedin.com^
||bat.bing.com^
||clarity.ms^$third-party
||newrelic.com^$third-party,script
||nr-data.net^
||sentry-cdn.com^$third-party,script
||branch.io^$third-party,script
! --- path patterns (conservative) ---
/pagead/js/adsbygoogle.js
/pagead/id?
/pagead/gen_204
/adsbygoogle.js
/ads/prebid
/prebid.js
/gpt.js$script,third-party
/show_ads_impl
/doubleclick/
/banners/ads/
/ad-manager/
@@||doubleclick.net/instream/ad_status.js^
! --- cosmetic ---
##.adsbygoogle
##ins.adsbygoogle
##[id^="google_ads_iframe"]
##[id^="div-gpt-ad"]
##[id^="google_ads_"]
##[data-ad-slot]
##[data-google-query-id]
##[data-ad-client]
##.ad-banner
##.ad-container
##.ad-slot
##.ad-wrapper
##.advert
##.advertisement
##.advertisement-banner
##.banner-ad
##.banner_ad
##.google-ad
##.googlead
##.sponsored-ad
##.taboola-widget
##[id^="taboola-"]
##.OUTBRAIN
##[id^="outbrain_widget"]
##.ob-widget
##[class*="adsbox"]
##.sidebar-ad
##.top-ad
##.leaderboard-ad
##amp-ad
##amp-embed
`;
